### ISSUE TITLE
docker pull timing out

### ISSUE THREAD

**Issue by osxi** [onmodulus/docker-run-node#3]
I get the following error when trying to pull the image:

```
$ docker pull onmodulus/docker-run-node:latest
Pulling repository docker.io/onmodulus/docker-run-node
Network timed out while trying to connect to https://index.docker.io/v1/repositories/onmodulus/docker-run-node/images. You may want to check your internet connection or if you are behind a proxy.
```

Strange because it looks like y'all have everything on https://hub.docker.com/r/onmodulus/.

**Comment by jackboberg** [comment]
Can you try again, it seems to be working fine for me. Perhaps just a network blip?

**Comment by osxi** [comment]
Weird-- yeah it works fine!
