### ISSUE TITLE
Runing sudo apt-get before modulus is deployed

### ISSUE THREAD

**Issue by HLGgithub** [onmodulus/docker-run-node#6]
Modulus is great, but I've hit a roadblock in transitioning our company over because we can't install (linux) packages before deployment, since a variety of our node / meteor apps need certain packages (like pdftk) installed on the deployed server. 

Perhaps a way to address this obstacle would be to allow the deployer to list the system packages that need to be installed in a configuration file, and then the system could run sudo apt-get install for each item in the list during deployment.

**Comment by theworkflow** [comment]
@HLGgithub thanks for submitting the issue and our apologies for getting back to you so late. Our run images are focused solely on running your applications. In regards to certain packages, you can create an issue on the build image for which dependencies you need installed.
